name: Sync Mozilla Central Repo. to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Mercurial
        run: |
          sudo apt-get update
          sudo apt-get install -y mercurial

      - name: Clone Mercurial repository
        run: |
          # hg clone https://hg.mozilla.org/mozilla-central/mobile/android repo
          hg clone --noupdate https://hg.mozilla.org/mozilla-central/ repo
          cd repo
          hg update mobile/android

      # - name: Pull latest changes from Mercurial
      #   run: |
      #     cd repo
      #     hg pull

      - name: Push changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git add .
          git commit -m "Sync from Mercurial"
          git remote add origin https://github.com/vs4vijay/firefox-focus.git
          git push --force origin main
