name: Sync Mozilla Central Repo. to GitHub

on:
  workflow_dispatch:
  schedule:
    # - cron: '0 0 * * *' # Run at midnight every day
    - cron: '0 0 * * 1' # Run at every monday

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Mercurial
        run: |
          sudo apt-get update
          sudo apt-get install -y mercurial

      - name: Clone Mercurial repository
        run: |
          hg clone --noupdate https://hg.mozilla.org/mozilla-central/ repo
          cd repo
          # hg update mobile/android

      - name: Configure git user
        run: |
          git config --global user.email "vs4vijay@gmail.com"
          git config --global user.name "vs4vijay"

      - name: Push changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git add -A
          git diff-index --quiet HEAD || git commit -m "Sync from Mercurial"
          git remote add origin https://github.com/vs4vijay/firefox-focus.git
          git push --force origin main
